version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - ./config/postfix/postfix-main.cf:/tmp/docker-mailserver/postfix-main.cf
    env_file:
    - .env
    - env-mailserver
    environment:
      - PERMIT_DOCKER=network
      - SMTP_ONLY=1
      - DEFAULT_RELAY_HOST=[smtp.gmail.com]:587
      - RELAY_HOST=[smtp.gmail.com]:587
      - POSTFIX_INET_PROTOCOLS=ipv4
      - ENABLE_SASLAUTHD=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SPOOF_PROTECTION=0
      - REPORT_RECIPIENT=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    networks:
      mail:
networks:
  mail:
    name: mail
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
